version: "3.3"
  
networks:
  net:
     driver: overlay
     attachable: true

services:
  logs:
    image: cquan808/build-logs:latest
    networks:
      - net
    volumes:
      - ./alchemy.log:/var/log/alchemy.log
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.labels.project == epicProject
#          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s